spring.application.name=group4-java-grader
spring.profiles.default=dev

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.locations=classpath:db/migration
spring.thymeleaf.check-template-location=false
