spring.application.name=group4-java-grader
spring.profiles.default=dev

server.port=8081

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.locations=classpath:db/migration
spring.flyway.ignore-migration-patterns=*:missing
spring.thymeleaf.check-template-location=false
server.servlet.session.timeout=30m
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
app.storage.submissions-root=./data/submissions
app.storage.grading-root=./data/grading
app.batch.worker-count=2
app.batch.queue-capacity=8
app.grading.timeout-millis=3000

